server {
    listen 443 ssl;
    server_name shushakov.cv.dsandy.cloud;

    ssl_certificate /etc/nginx/certs.cloud/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs.cloud/privkey.pem;

    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html;
      expires off;
      add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}